@hostname = {{$dotenv HOSTNAME}}
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}

### Login
# @name login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
	"email": "php.chandan@gmail.com",
	"password": "10091986"
}

### Google Login
# @name google_login
GET {{host}}/api/v1/auth/google
Content-Type: application/json

###
@token = {{login.response.body.accessToken}}
GET {{host}}/api/v1/auth/protected
Content-Type: application/json
Authorization: Bearer {{token}}
