export default {
	port: process.env.PORT || 3050,
	log_level: process.env.LOG_LEVEL || "info",
	mongo_url: process.env.MONGO_URL,
	jwt_secret: process.env.JWT_SECRET,
	access_token_public_key: process.env.ACCESS_TOKEN_PUBLIC_KEY,
	access_token_private_key: process.env.ACCESS_TOKEN_PRIVATE_KEY,
	refresh_token_public_key: process.env.REFRESH_TOKEN_PUBLIC_KEY,
	refresh_token_private_key: process.env.REFRESH_TOKEN_PRIVATE_KEY,
	google_client_id: process.env.GOOGLE_CLIENT_ID,
	google_client_secret: process.env.GOOGLE_CLIENT_SECRET,
	google_callback_url: process.env.GOOGLE_CALLBACK_URL,
	aws_access_id: process.env.AWS_ACCESS_KEY_ID,
	aws_access_secret: process.env.AWS_SECRET_ACCESS_KEY,
	aws_default_region: process.env.AWS_DEFAULT_REGION,
	aws_bucket: process.env.AWS_BUCKET,
	aws_endpoint: process.env.AWS_ENDPOINT,
};
